name:  Documentation
description: Mejoras o correcciones en la documentaci贸n
labels: ["documentation"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Tipo de cambio
      options:
        - Correcci贸n de error
        - Informaci贸n faltante
        - Clarificaci贸n necesaria
        - Nueva secci贸n
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Ubicaci贸n
      description: Qu茅 archivo o secci贸n necesita cambios
      placeholder: "README.md, secci贸n de instalaci贸n"
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Cambio sugerido
      description: Qu茅 deber铆a decir o a帽adirse
    validations:
      required: true
